psql -U postgres -d postgres -c "CREATE TABLE ciudades (ciudad VARCHAR(40) PRIMARY KEY, estado VARCHAR(40) NOT NULL)"
psql -U postgres -d postgres -c "CREATE TABLE zip_codes (zip_code INTEGER PRIMARY KEY, lat NUMERIC NOT NULL, long NUMERIC NOT NULL, ciudad VARCHAR (40) NOT NULL)"
psql -U postgres -d postgres -c "CREATE TABLE clientes (cliente_id VARCHAR(40) PRIMARY KEY, cliente_id_unico VARCHAR (40) NOT NULL, cliente_zip_code INTEGER NOT NULL)"
psql -U postgres -d postgres -c "CREATE TABLE vendedores (vendedor_id VARCHAR(40) PRIMARY KEY, vendedor_zip_code INTEGER NOT NULL)"
psql -U postgres -d postgres -c "CREATE TABLE traduccion_nombre (categoria_port VARCHAR PRIMARY KEY, categoria_ingles VARCHAR NOT NULL)"
psql -U postgres -d postgres -c "CREATE TABLE productos(producto_id VARCHAR PRIMARY KEY, categoria VARCHAR, nombre_largo INTEGER, descripcion_prod_largo INTEGER, cantidad_fotos INTEGER, prod_peso_grs INTEGER, prod_largo_cm INTEGER, prod_alto_cm INTEGER, prod_ancho_cm INTEGER)"
psql -U postgres -d postgres -c "CREATE TABLE ordenes(orden_id VARCHAR PRIMARY KEY, cliente_id VARCHAR, status VARCHAR, compra_timestamp TIMESTAMP, aprobado_timestamp TIMESTAMP, entrega_transporte_timestamp TIMESTAMP, entrega_timestamp TIMESTAMP, entrega_estimada_timestamp TIMESTAMP)"
psql -U postgres -d postgres -c "CREATE TABLE items_ordenes(item_id VARCHAR PRIMARY KEY, item_numero_orden INTEGER, producto_id VARCHAR, vendedor_id VARCHAR, fecha_entrega_maxima TIMESTAMP, precio_item NUMERIC, precio_flete_item NUMERIC)"
psql -U postgres -d postgres -c "CREATE TABLE pagos(pago_id VARCHAR PRIMARY KEY, numero_subpago INTEGER, medio_pago VARCHAR, numero_cuotas INTEGER, importe_pago NUMERIC)"
psql -U postgres -d postgres -c "CREATE TABLE reviews(review_id VARCHAR PRIMARY KEY, orden_id VARCHAR, review_score INTEGER, titulo VARCHAR, mensaje TEXT, fecha_creacion TIMESTAMP, fecha_respuesta TIMESTAMP)" 
